### ISSUE TITLE
Casting skills along the way.

### ISSUE THREAD

**Issue by RobotGaston** [hectorgimenez/koolo#37] opened 2023-10-12 00:51 UTC
Thank you for further improvements. Thank you for looking into cta and buffing improvements.

There is a problem with a new added "buffing" system in - 7fee717

Character - sorceress.

She has  CallToArms OnSwap.

On her way to an objective she can randomly stop during teleporting, in the middle of location where she is not supposed to, then select frothen armor and start casting it 10x times or so (freezing in one place),  after that, character switching back to teleport and proceed to the final destination point.

Such behaviour was never observed in a "previous main build version"

Could you look into this please?
thank you :)

P.S. I'm not experiencing any difficulties with waypoint menu.
Character can select all the acts, wps with 100% success...

**Comment by hectorgimenez** [comment] 2023-10-12 03:27
mmmm, definitely that's not the expected behavior 🤣
In theory with the new implementation (not very tested at this point, honestly) the expected behavior should be: when character gets out of the town, if any buff is missing, it will rebuff all of them (including cta), and continue teleporting, but at anytime it detects again a missing buff will run the buff action again, but it should be very fast, so yeah if your frozen armor expires during teleport it should stop, rebuff and continue teleporting.

Are you using Frozen, Shiver or Chilling armor? is CTA used also when that thing happens? it's buffing also just at the beginning when character uses the WP for the first time in a game?

**Comment by RobotGaston** [comment] 2023-10-12 09:20
-I'm using Frozen armour :)

-CTA is used when this happens :) (I have CTA on the swap in 2nd slot).

-And yes, it is buffing at the start of the run (at the waypoint when character uses wp for the first time :) ).

Character casts BO from the CTA at the start of the run.
Then character going to his target and during teleportation to it it stops in random place in a location in pack of mobs, and starts casting real quick Battle orders, Battle command, and frozen armour sticking on the casting frozen armour. Repeating casting frozen armour 8-10x times, then unsticking, switching to teleport skill and proceed to teleport further  to it's target...

After the explanation.
The problem I suspect is - character, by some reason is incorrectly detecting that he is out of buff (along the way while teleporting), which is triggering it to recast the buff it thinks is missing. While in reality the buffs are ON and active...

It happen not all the time, just time to time...It needs to be caught...:)

**Comment by RobotGaston** [comment] 2023-10-12 10:16
Just observed.
-Character is not casting buffs, and the start of each run.

When in game, if the character still has a buffs on it from a previous run it was doing in the same game, it's NOT casting a rebuffs in a new next run. It just starting a next run, goes to a waypoint and goes straight to target skipping casting a buffs at waypoint in a location (which it supposed to do). 

Next run is started. Character going to wp, SKIPPING buffs, and just starting to teleport to the final destination. 
Somewhere in the middle of the teleportation. in a random place. character stops, RECASTS - BO -BC -FO - gets stuck on recasting FO - keeping it casting 8-10 times staying in place. and thennn being unable to unstick of recasting FO ending game with this :

DEBUG	internal/bot.go:92	Load completed, continuing execution
DEBUG	action/buff.go:80	CTA found: swapping weapon and casting Battle Command / Battle Orders
DEBUG	action/buff.go:44	Buffing...
DEBUG	health/belt_manager.go:32	Using HealingPotion potion on Mercenary [Column: 1]. HP: 90
WARN	internal/single_supervisor.go:77	Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: MoveToStep: path could not be calculated, maybe there is an obstacle or a flying platform (arcane sanctuary). Game total time: 369.72s
github.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start
	C:/Users/........../internal/single_supervisor.go:77
main.main.func2
	C:/Users/........./cmd/koolo/main.go:96
golang.org/x/sync/errgroup.(*Group).Go.func1
	C:/.........../go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:75

:)

**Comment by hectorgimenez** [comment] 2023-10-13 11:36
I pushed a small change, will not fix the problem but I think it will mitigate the effect, now it should be casting the buff sequence at the start of each run.

By the way, could you please confirm when this is happening to you, that really really that at least ONE buff was missing? I've been trying it for a while and for me is always casting the buff only when at least one is missing. I don't have CTA right now so testing that part is difficult.

**Comment by RobotGaston** [comment] 2023-10-13 12:13
thank you for the update, Hector! :) 
Was waiting for the changes/tweaks impatiently... :) as the https://github.com/hectorgimenez/koolo/commit/7fee71774a47f3dbd23d744955a54ea60bbbd3c0 was unusable for me at that state.. )

I put the 3df89d9 on test right now. 

Will report back :)

**Comment by hectorgimenez** [comment] 2023-10-13 14:37
btw, the "usecta" configuration flag was removed also, so now it's ignored. If the tool detect the CTA equipped and the keybindings assigned it will try to use it automatically, if you don't have CTA or keybindings are not set, will skip. So you don't need to keep switching on/off the flag.

**Comment by RobotGaston** [comment] 2023-10-13 15:21
Ahh I see.. :)

okay now, at the start of the run on the fist battlefield wp sorceress giving self bo: (double times)

internal/bot.go:92	Load completed, continuing execution
action/buff.go:84	CTA found: swapping weapon and casting Battle Command / Battle Orders
action/buff.go:48	Buffing...
health/belt_manager.go:37	Using HealingPotion potion [Column: 2]. HP: 84 MP: 229
action/buff.go:84	CTA found: swapping weapon and casting Battle Command / Battle Orders
action/buff.go:48	Buffing...

I observed full stop at arcane sanctuary, uninformatively:

Sorc got to waypoint - arcane sanctuary - teleported 1 step away, 
performed this on a battlefield: (In a location away from safe waypoint zone)

INFO	action/waypoint.go:99	Traversing areas to reach destination	{"areas": [74]}
DEBUG	internal/bot.go:85	Loading screen detected, waiting until loading screen is gone
DEBUG	internal/bot.go:92	Load completed, continuing execution
DEBUG	action/buff.go:84	CTA found: swapping weapon and casting Battle Command / Battle Orders
DEBUG	action/buff.go:48	Buffing...
DEBUG	health/belt_manager.go:37	Using HealingPotion potion [Column: 2]. HP: 84 MP: 229
DEBUG	action/buff.go:84	CTA found: swapping weapon and casting Battle Command / Battle Orders
DEBUG	action/buff.go:48	Buffing...

and after that freezed in 1 spot with a full stop, ...not moving further. I waited for about 1 minute then terminated program...manually. No errors where given.
INFO	internal/supervisor.go:32	Shutting down NOWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.

Just witnessed also this: (but more carefully):

1st run in the game, 
sorc, correctly loaded in waypoint, 
gave herself a BO with CTA,
aaaanddd
instead of switching to teleport and proceed to the destination, she FREEZED in 1 spot (just like in arcane previously), unable to select and switch to teleport skill, - (attacking skill just showing melee attack) :(

I terminated manually and I got this "spam" in a debug window while where doing it: 

"C:\Users\...........>wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww^W^W^W^W^W^Wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"

Program by some reason after bo got stuck in sending with keyboard the line is written above...

This is floating problem again....:( Sometimes she goes okay, and sometimes she's getting into this situation...with "freezing after bo" behaviour...with the incorrect keyboard sends... 

I'm stooping observation and using "[3df89d9](https://github.com/hectorgimenez/koolo/commit/3df89d980d54366fc56e891bfe0b4ea77e1a545c)" at this point...please...send fixes? :)

**Comment by hectorgimenez** [comment] 2023-10-14 13:30
> Also, when character "reboes" at waypoint when goes with a next "script", It casting only Battle orders for example - Ignoring to cast a Battle command or vice versa... (At first run of the game character is correctly always Casting both BO and BC, but in next runs - in some runs (in the same game) it casts both skills, and in some,- only 1 of 2 skills available...).
I suppose it might be somehow be connected with the "character state detection" ...I think it's better to force it to recast both skills (BO and BC) no matter if they are ON or OFF at the time of the cast at the start of the every run....Also casting system should be calculated and work from the lowest roll possible on the call to arms weapon :)

I have the feeling this is related to the skill selection speed, maybe it's too fast, I added an small delay, so hopefully it will help.

I hope the teleport problem is fixed now also, could you check with the latest changes if the situation is better AND is rebuffing when buffs are down (and not stuck rebuffing forever)? As said, difficult for me to test since I don't have CTA right now.

**Comment by RobotGaston** [comment] 2023-10-14 19:07
Thank you. Put it on test now.

**Comment by hectorgimenez** [comment] 2023-10-15 01:50
Do you have discord? maybe we can talk there on how we can test this.

**Comment by RobotGaston** [comment] 2023-10-15 08:27
Yes, I Do have a discord, :) Where should I join?

and

testing (https://github.com/hectorgimenez/koolo/commit/2176149f66a567930751daa479f1ff3d09514a1f)
2176149

now :) 
Thank you for changes.

**Comment by hectorgimenez** [comment] 2023-10-15 09:22
@RobotGaston https://discord.gg/tDMSGDvDEM try this invite link

**Closed** 2023-10-19 14:41 UTC
